openapi: 3.0.1
info:
  title: IDeaS Group Block Master API
  description: >-
    IDeaS Group Block Master API
  contact:
    name: IDeaS Dev
  version: v1
paths:
  '/api/public/group/v1':
    post:
      tags:
        - IDeaSGroupBlockMasterV1
      summary: 'save collection of group block masters'
      description: 'In success case, Http Code 202 will be returned'
      operationId: saveGroupBlockMasters
      requestBody:
        description: GroupBlockMasters to save
        required: true
        content:
          application/json:
            schema:
              type: "array"
              items:
                $ref: '#/components/schemas/IDeaSGroupBlockMaster'
            examples:
              SampleGroupDefinite:
                $ref: '#/components/examples/SampleGroupDefiniteExample'
              SampleGroupCancelled:
                $ref: '#/components/examples/SampleGroupCancelledExample'
      responses:
        '202':
          description: Group Block Master posted
          content: { }
        '400':
          description: Bad request
          content:
            '*/*':
              schema:
                $ref: 'common.yaml#/components/schemas/ApiError'
        '500':
          description: Internal server error
          content:
            '*/*':
              schema:
                $ref: 'common.yaml#/components/schemas/ApiError'
components:
  schemas:
    IDeaSGroupBlockDetail:
      type: object
      required:
        - occupancyDate
        - roomTypeCode
        - blocks
        - pickup
        - originalBlocks
        - originalCurrencyCode
      properties:
        occupancyDate:
          type: string
          format: date
          description: occupancy date
        roomTypeCode:
          type: string
          description: room type code
        blocks:
          type: integer
          format: int32
          description: number of blocks
        pickup:
          type: integer
          format: int32
          description: Rooms picked up from the block
        originalBlocks:
          type: integer
          format: int32
          description: Original/initial rooms blocked
        rate:
          type: number
          description: rate
        twoPersonRate:
          type: number
          description: two person rate
        threePersonRate:
          type: number
          description: three person rate
        fourPersonRate:
          type: number
          description: four person rate
        singlePersonOccupancy:
          type: number
          description: single person occupancy
        twoPersonOccupancy:
          type: number
          description: two person occupancy
        threePersonOccupancy:
          type: number
          description: three person occupancy
        fourPersonOccupancy:
          type: number
          description: four person occupancy
        originalCurrencyCode:
          type: string
          description: original currency code
        extraAdultRate:
          type: number
          description: extra rate
        extraChildRate:
          type: number
          description: extra child rate
    GroupService:
      type: object
      required:
        - startDate
        - endDate
        - serviceName
        - serviceValue
        - inclusive
      properties:
        serviceName:
          type: string
          description: service name
        serviceValue:
          type: number
          description: service value
        inclusive:
          type: boolean
          description: inclusive
        startDate:
          type: string
          format: date
          description: start date
        endDate:
          type: string
          format: date
          description: end date
    IDeaSGroupBlockMaster:
      type: object
      required:
        - clientCode
        - propertyCode
        - groupCode
        - name
        - marketSegmentCode
        - startDate
        - endDate
        - groupTypeCode
        - groupBlocks
        - bookingDate
        - cutoffDays
        - cutoffDate
        - pickupTypeCode
        - groupStatusCode
      properties:
        clientCode:
          type: string
          description: client code
        propertyCode:
          type: string
          description: property code
        correlationId:
          type: string
          description: unique id associated with this object
        statisticsCorrelationId:
          type: string
          description: id to associate the group record to a set of statistics data
        groupCode:
          type: string
          description: group block code
        action:
          type: string
          description: action associated with group block
          enum:
            - BOOK
            - QUOTE
            - HOLD
            - INITIATE
            - IGNORE
            - MODIFY
            - COMMIT
            - CANCEL
        name:
          type: string
          description: name of group block
        description:
          type: string
          description: description of group block
        masterGroupCode:
          type: string
          description: master group code
        groupStatusCode:
          type: string
          description: group status code
        originalGroupStatusCode:
          type: string
          description: original group status code
        marketSegmentCode:
          type: string
          description: market segment code
        startDate:
          type: string
          description: start date
          format: date
        endDate:
          type: string
          description: end date
          format: date
        groupTypeCode:
          type: string
          description: group type code
        bookingDate:
          type: string
          format: date
          description: booking date
        pickupTypeCode:
          type: string
          description: pickup type code
        sourcePickupTypeCode:
          type: string
          description: source pickup type code
        cancelDate:
          type: string
          format: date-time
          description: cancel date
        bookingType:
          type: string
          description: booking type
        salesPerson:
          type: string
          description: sales person
        cutoffDays:
          type: integer
          format: int32
          description: cutoff days
        cutoffDate:
          type: string
          description: cutoff date
          format: date
        groupId:
          type: string
          description: group id
        masterGroupId:
          type: string
          description: master group id
        groupBlocks:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/IDeaSGroupBlockDetail'
        services:
          type: array
          items:
            $ref: '#/components/schemas/GroupService'
        profileId:
          type: string
          description: profile Id
        rateCode:
          type: string
          description: rate code
  examples:
    SampleGroupDefiniteExample:
      value:
        - clientCode: "WHG"
          propertyCode: "SAND02CN"
          groupCode: "TEST_GROUP_CODE_1"
          action: null
          name: "TEST_GROUP_NAME_1"
          description: "TEST_GROUP_DESCRIPTION_1"
          masterGroupCode: "TEST_MASTER_GROUP_CODE_1"
          groupStatusCode: "DEFINITE"
          originalGroupStatusCode: "ACT"
          marketSegmentCode: "TEST_MS_CODE_1"
          startDate: "2016-08-10"
          endDate: "2016-08-12"
          earliestArrivalDate: "2016-08-10"
          latestDepartureDate: "2016-08-11"
          groupTypeCode: "GROUP"
          bookingDate: "2016-08-01"
          pickupTypeCode: "INDV"
          sourcePickupTypeCode: "RLST"
          cancelDate: null
          bookingType: "TEST_BOOKING_TYPE_1"
          salesPerson: "TEST_SALES_PERSON_1"
          cutoffDays: 5
          cutoffDate: "2016-07-20"
          groupId: "TEST_GROUP_ID_1"
          masterGroupId: "TEST_MASTER_GROUP_ID_1"
          groupBlocks:
            - occupancyDate: "2016-08-10"
              roomTypeCode: "C1K"
              blocks: 26
              pickup: 26
              originalBlocks: 26
              rate: 190.00000
              twoPersonRate: 190.00000
              threePersonRate: 217.27273
              fourPersonRate: 244.54545
              singlePersonOccupancy: 1
              twoPersonOccupancy: 2
              threePersonOccupancy: 3
              fourPersonOccupancy: 4
              originalCurrencyCode: "USD"
              extraAdultRate: 100.25
              extraChildRate: 95.25
              groupBlockDetailId: null
            - occupancyDate: "2016-08-11"
              roomTypeCode: "C1K"
              blocks: 26
              pickup: 26
              originalBlocks: 26
              rate: 190.00000
              twoPersonRate: 190.00000
              threePersonRate: 217.27273
              fourPersonRate: 244.54545
              singlePersonOccupancy: 1
              twoPersonOccupancy: 2
              threePersonOccupancy: 3
              fourPersonOccupancy: 4
              originalCurrencyCode: "USD"
              extraAdultRate: 100.25
              extraChildRate: 95.25
              groupBlockDetailId: null
            - occupancyDate: "2016-08-10"
              roomTypeCode: "C2D"
              blocks: 2
              pickup: 2
              originalBlocks: 0
              rate: 190.00000
              twoPersonRate: 190.00000
              threePersonRate: 217.27273
              fourPersonRate: 244.54545
              singlePersonOccupancy: 1
              twoPersonOccupancy: 2
              threePersonOccupancy: 3
              fourPersonOccupancy: 4
              originalCurrencyCode: "USD"
              extraAdultRate: 100.25
              extraChildRate: 95.25
              groupBlockDetailId: null
            - occupancyDate: "2016-08-11"
              roomTypeCode: "C2D"
              blocks: 2
              pickup: 2
              originalBlocks: 0
              rate: 190.00000
              twoPersonRate: 190.00000
              threePersonRate: 217.27273
              fourPersonRate: 244.54545
              singlePersonOccupancy: 1
              twoPersonOccupancy: 2
              threePersonOccupancy: 3
              fourPersonOccupancy: 4
              originalCurrencyCode: "USD"
              extraAdultRate: 100.25
              extraChildRate: 95.25
              groupBlockDetailId: null
          services:
            - serviceName: "BKFAST"
              serviceValue: 10.25
              inclusive: true
              inclusionType: "INCLUDE"
              roomRevenuePackage: true
              startDate: "2016-08-10"
              endDate: "2016-08-15"
          profileId: "66233346"
          rateCode: "TEST_RATE_CODE_1"
    SampleGroupCancelledExample:
      value:
        - clientCode: "WHG"
          propertyCode: "SAND02CN"
          groupCode: "TEST_GROUP_CODE_2"
          action: null
          name: "TEST_GROUP_NAME_2"
          description: "TEST_GROUP_DESCRIPTION_2"
          masterGroupCode: "TEST_MASTER_GROUP_CODE_2"
          groupStatusCode: "CANCELLED"
          originalGroupStatusCode: "CAN"
          marketSegmentCode: "TEST_MS_CODE_2"
          startDate: "2016-08-10"
          endDate: "2016-08-12"
          earliestArrivalDate: "2016-08-10"
          latestDepartureDate: "2016-08-11"
          groupTypeCode: "GROUP"
          bookingDate: "2016-08-01"
          pickupTypeCode: "INDV"
          sourcePickupTypeCode: "RLST"
          cancelDate: null
          bookingType: "TEST_BOOKING_TYPE_2"
          salesPerson: "TEST_SALES_PERSON_2"
          cutoffDays: 5
          cutoffDate: "2016-07-20"
          groupId: "TEST_GROUP_ID_2"
          masterGroupId: "TEST_MASTER_GROUP_ID_2"
          groupBlocks:
            - occupancyDate: "2016-08-10"
              roomTypeCode: "C1K"
              blocks: 26
              pickup: 26
              originalBlocks: 26
              rate: 190.00000
              twoPersonRate: 190.00000
              threePersonRate: 217.27273
              fourPersonRate: 244.54545
              singlePersonOccupancy: 1
              twoPersonOccupancy: 2
              threePersonOccupancy: 3
              fourPersonOccupancy: 4
              originalCurrencyCode: "USD"
              extraAdultRate: 100.25
              extraChildRate: 95.25
              groupBlockDetailId: null
            - occupancyDate: "2016-08-11"
              roomTypeCode: "C1K"
              blocks: 26
              pickup: 26
              originalBlocks: 26
              rate: 190.00000
              twoPersonRate: 190.00000
              threePersonRate: 217.27273
              fourPersonRate: 244.54545
              singlePersonOccupancy: 1
              twoPersonOccupancy: 2
              threePersonOccupancy: 3
              fourPersonOccupancy: 4
              originalCurrencyCode: "USD"
              extraAdultRate: 100.25
              extraChildRate: 95.25
              groupBlockDetailId: null
            - occupancyDate: "2016-08-10"
              roomTypeCode: "C2D"
              blocks: 2
              pickup: 2
              originalBlocks: 0
              rate: 190.00000
              twoPersonRate: 190.00000
              threePersonRate: 217.27273
              fourPersonRate: 244.54545
              singlePersonOccupancy: 1
              twoPersonOccupancy: 2
              threePersonOccupancy: 3
              fourPersonOccupancy: 4
              originalCurrencyCode: "USD"
              extraAdultRate: 100.25
              extraChildRate: 95.25
              groupBlockDetailId: null
            - occupancyDate: "2016-08-11"
              roomTypeCode: "C2D"
              blocks: 2
              pickup: 2
              originalBlocks: 0
              rate: 190.00000
              twoPersonRate: 190.00000
              threePersonRate: 217.27273
              fourPersonRate: 244.54545
              singlePersonOccupancy: 1
              twoPersonOccupancy: 2
              threePersonOccupancy: 3
              fourPersonOccupancy: 4
              originalCurrencyCode: "USD"
              extraAdultRate: 100.25
              extraChildRate: 95.25
              groupBlockDetailId: null
          services:
            - serviceName: "BKFAST"
              serviceValue: 10.25
              inclusive: true
              inclusionType: "INCLUDE"
              startDate: "2016-08-10"
              endDate: "2016-08-15"
          profileId: 66233346
          rateCode: "TEST_RATE_CODE_2"

  securitySchemes:
    oAuth2ClientCredentialsStage:
      type: oauth2
      description: description
      flows:
        clientCredentials:
          tokenUrl: https://fds.ideasrms.com/api/uis/internal_m2m/oauth2/token
          scopes:
            write: allows modifying resources
            read: allows reading resources
    oAuth2ClientCredentials:
      type: oauth2
      description: description
      flows:
        clientCredentials:
          tokenUrl: https://fds.ideasrms.com/api/uis/internal_m2m/oauth2/token
          scopes:
            write: allows modifying resources
            read: allows reading resources

security:
  - oAuth2ClientCredentialsStage:
      - read
      - write
  - oAuth2ClientCredentials:
      - read
      - write