openapi: 3.0.1
info:
  title: IDeaS Reservations API
  description: >-
    API for creating reservations
  version: v1
paths:
  /api/public/reservation/v1:
    post:
      tags:
        - IDeaSReservationV1
      summary: save reservations
      description : some description here...
      operationId: saveReservations
      requestBody:
        description: Reservations to save
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/IDeaSReservation'
              minItems: 1
            examples:
              placeholderExample:
                $ref: '#/components/examples/placeholderReservationExample'

      responses:
        '202':
          description: Accepted
        '400':
          description: Bad request
          content:
            '*/*':
              schema:
                $ref: 'common.yaml#/components/schemas/ApiError'
        '500':
          description: Internal server error
          content:
            '*/*':
              schema:
                $ref: 'common.yaml#/components/schemas/ApiError'
components:
  schemas:
    IDeaSReservation:
      type: object
      required:
        - reservationId
        - clientCode
        - propertyCode
        - bookingDate
        - status
        - roomStays
        - numberOfRooms
        - channel
      properties:
        bookingDate:
          type: string
          description: date of the booking
          format: date-time
        cancellationDate:
          type: string
          description: date reservation was cancelled
          format: date-time
        cancellationId:
          type: string
          description: cancellation id
        cancellationReason:
          type: string
          description: reason reservation was cancelled
        channel:
          type: string
          description: booking channel reservation was made with
        clientCode:
          type: string
          description: client code associated with reservation
        confirmationNumber:
          type: string
          description: confirmation number of the reservation
        correlationId:
          type: string
          description: correlation ID
        customerValue:
          type: string
          description: customer value
        multiReservationId:
          type: string
          description: multi reservation id
        nationality:
          type: string
          description: nation booking was made in
        numberOfRooms:
          type: integer
          format: int32
          description: number of rooms in reservation
        previousSharers:
          type: array
          items:
            type: string
          description: previous sharers in reservations
        primarySharer:
          type: boolean
          description: primary sharer
        profileId:
          type: string
          description: id of profile associated with this reservation
        propertyCode:
          type: string
          description: property code associated with this reservation
        reservationId:
          type: string
          description: id of reservation
        roomStays:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/IDeaSRoomStay'
        profiles:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/IDeaSProfile'
        sharers:
          type: array
          items:
            type: string
          description: list of sharers
        status:
          type: string
          enum:
            - RESERVED
            - CANCELLED
            - IN_HOUSE
            - CHECKED_OUT
            - NO_SHOW
          description: status of reservation
          format: enum
        stayRevenue:
          $ref: '#/components/schemas/StayRevenue'
    IDeaSRoomStay:
      type: object
      required:
        - rates
        - arrivalDate
        - departureDate
        - bookedRoomTypeCode
        - marketCode
        - roomTypeCode
        - rateCode
        - sourceBookingCode
        - numberOfChildren
        - numberOfAdults
        - bookingType
      properties:
        arrivalDate:
          type: string
          format: date
          description: date of arrival
        bookedRoomTypeCode:
          type: string
          description: booked room type code
        bookingType:
          type: string
          description: booking type
        currencyExchangeId:
          type: string
          description: currency exchange ID
        departureDate:
          type: string
          format: date
          description: date of departure
        groupBlockCode:
          type: string
          description: group block code
        roomTypeCode:
          type: string
          description: room type code
        marketCode:
          type: string
          description: market code
        numberOfAdults:
          type: integer
          format: int32
          description: number of adults
        numberOfChildren:
          type: integer
          format: int32
          description: number of children
        originalCurrencyCode:
          type: string
          description: original curency code
        rateCode:
          type: string
          description: rate code
        rates:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/IDeaSRate'
        revenue:
          $ref: '#/components/schemas/Revenue'
        roomNumber:
          type: string
          description: room number
        services:
          type: array
          items:
            $ref: '#/components/schemas/Service'
        sourceBookingCode:
          type: string
          description: source booking code
    IDeaSProfile:
      type: object
      required:
        - id
        - profileType
        - name
      properties:
        id:
          type: string
          description: id
        profileType:
          type: string
          enum:
            - GUEST
            - CORPORATE
            - TRAVEL_AGENT
            - COMPANY
            - AGENT
            - GROUP
            - WHOLESALER
          description: type of profile
        context:
          type: string
          description: profile context
        name:
          type: string
          description: profile name
    StayRevenue:
      type: object
      properties:
        daily:
          type: array
          items:
            $ref: '#/components/schemas/DailyRevenue'
        stayMessageIds:
          type: array
          items:
            type: string
          description: stay message ids
        summary:
          $ref: '#/components/schemas/Revenue'
    Service:
      type: object
      properties:
        endDate:
          type: string
          format: date
          description: end date of service
        inclusionType:
          type: string
          enum:
            - INCLUDE
            - SEPARATE
            - COMBINED
            - OTHER
          description: inclusion type
        inclusive:
          type: boolean
          description: is the service inclusive
        reservationPackage:
          type: boolean
          description: reservation package
        roomRevenuePackage:
          type: boolean
          description: room revenue package
        serviceName:
          type: string
          description: name of service
        serviceValue:
          type: number
          description: value of service
        startDate:
          type: string
          format: date
          description: start date of service
    DailyRevenue:
      type: object
      allOf:
        - $ref: '#/components/schemas/Revenue'
        - type: object
          properties:
            transactionDate:
              type: string
              format: date
    Revenue:
      type: object
      properties:
        beverageRevenue:
          type: number
          description: beverage revenue
        foodRevenue:
          type: number
          description: food revenue
        otherRevenue:
          type: number
          description: other revenue
        roomRevenue:
          type: number
          description: room revenue
        totalRevenue:
          type: number
          description: total
    IDeaSRate:
      type: object
      required:
        - rateValue
        - startDate
        - endDate
      properties:
        currencyExchangeId:
          type: string
          description: currency exchange ID
        endDate:
          type: string
          format: date
          description: end date
        grossRate:
          type: number
          description: gross rate
        originalCurrencyCode:
          type: string
          description: original currency code
          format: TODO #TODO: what do currency codes look like, add validation?
        rateValue:
          type: number
          description: rate value
        startDate:
          type: string
          format: date
          description: start date
  examples:
    placeholderReservationExample:
      value:
        - primarySharer: true
          bookingDate: "2022-01-01T12:23:34Z"
          cancellationDate: "2022-01-01T12:23:44Z"
          cancellationId: "ABC123"
          cancellationReason: "Event was cancelled"
          channel: "Expedia"
          clientCode: "WHG"
          confirmationNumber: "ABC123"
          nationality: "US"
          numberOfRooms: 3
          previousSharers: ["ABC", "123"]
          profileId: "987ABC"
          propertyCode: "SAND02CN"
          reservationId: "TEST_IDEAS_API_1"
          roomStays:
            - arrivalDate: "2022-08-20"
              bookedRoomTypeCode: "bookedRT"
              bookingType: "bkTy"
              currencyExchangeId: "1"
              departureDate: "2022-08-21"
              groupBlockCode: "Grp1"
              roomTypeCode: "RT"
              marketCode: "MS"
              numberOfAdults: "1"
              numberOfChildren: "2"
              originalCurrencyCode: "USD"
              rateCode: "RC1"
              rates:
                - currencyExchangeId: "1"
                  endDate: "2022-08-21"
                  grossRate: "100.25"
                  originalCurrencyCode: "USD"
                  rateValue: "100.45"
                  startDate: "2022-08-20"
              revenue:
                beverageRevenue: "100.25"
                foodRevenue: "200.25"
                otherRevenue: "300.25"
                roomRevenue: "400.25"
                totalRevenue: "500.25"
              roomNumber: "100"
              sourceBookingCode: "srcBkCd"
          profiles:
            - id: "1"
              profileType: "COMPANY"
              context: "profContext"
              name: "profName"
          sharers: ["123", "ABC"]
          status: "RESERVED"
          stayRevenue:
            daily:
              - beverageRevenue: "100.25"
                foodRevenue: "200.25"
                otherRevenue: "300.25"
                roomRevenue: "400.25"
                totalRevenue: "500.25"
                transactionDate: "2022-08-20"
            stayMessageIds: ["12234", "12334"]
            summary:
              beverageRevenue: "777.25"
              foodRevenue: "777.35"
              otherRevenue: "777.45"
              roomRevenue: "777.55"
              totalRevenue: "777.65"
          daily:
            beverageRevenue: "100.25"
            foodRevenue: "200.25"
            otherRevenue: "300.25"
            roomRevenue: "400.25"
            totalRevenue: "500.25"
            transactionDate: "2022-08-20"
            stayMessageIds: [ "12234", "12334" ]
            summary:
              beverageRevenue: "777.25"
              foodRevenue: "777.35"
              otherRevenue: "777.45"
              roomRevenue: "777.55"
              totalRevenue: "777.65"

  securitySchemes:
    oAuth2ClientCredentialsStage:
      type: oauth2
      description: description
      flows:
        clientCredentials:
          tokenUrl: https://fds.ideasrms.com/api/uis/internal_m2m/oauth2/token
          scopes:
            write: allows modifying resources
            read: allows reading resources
    oAuth2ClientCredentials:
      type: oauth2
      description: description
      flows:
        clientCredentials:
          tokenUrl: https://fds.ideasrms.com/api/uis/internal_m2m/oauth2/token
          scopes:
            write: allows modifying resources
            read: allows reading resources

security:
  - oAuth2ClientCredentialsStage:
      - read
      - write
  - oAuth2ClientCredentials:
      - read
      - write