openapi: 3.0.1
info:
  title: IDeaS REST API
  description: >-
    IDEAS canonical Activity API
  contact:
    name: IDeaS Dev
  version: 0.0.1-ALPHA
paths:
  '/api/public/activity/room-type-market-segment/v1':
    post:
      tags:
        - IDeaSRoomTypeMarketSegmentActivityV1
      summary: 'Post Room Type Market Segment Activity for a property for the async processing'
      description: 'In success case, Http Code 202 will be returned'
      operationId: postRoomTypeMarketSegmentActivityV1
      requestBody:
        description: "Room Type Market Segment list to process"
        required: true
        content:
          application/json:
            schema:
              type: "array"
              items:
                $ref: "#/components/schemas/IDeaSRoomTypeMarketSegmentActivity"
              oneOf:
                - minItems: 1
                  maxItems: 1000
            examples:
              placeholderExample:
                $ref: '#/components/examples/SampleRoomTypeMarketSegmentActivity'
      responses:
        '202':
          description: Room Type Market Segment Activity posted
          content: {}
        '400':
          description: Bad request
          content:
            '*/*':
              schema:
                $ref: 'common.yaml#/components/schemas/ApiError'
        '500':
          description: Internal server error
          content:
            '*/*':
              schema:
                $ref: 'common.yaml#/components/schemas/ApiError'
components:
  schemas:
    IDeaSRoomTypeMarketSegmentActivity:
      type: object
      required:
        - roomTypeCode
        - marketSegmentCode
      allOf:
        - $ref: 'summaryActivity.yaml#/components/schemas/SummaryActivity'
        - type: object
          properties:
            roomTypeCode:
              type: string
            marketSegmentCode:
              type: string
  examples:
    SampleRoomTypeMarketSegmentActivity:
      value:
        - clientCode: "WHG"
          propertyCode: "SAND02CN"
          roomsSold: 5
          arrivals: 7
          departures: 39
          cancellations: 15
          noShows: 16
          roomRevenue: 100.75
          foodRevenue: 201.35
          totalRevenue: 301.42
          occupancyDate: "2020-10-03"
          fiscalDate: "2020-10-02"
          correlationId: "11292d1b6-55c8-4c84-a09c-7bb74403d156"
          noShowRoomRevenue: 502.36
          marketSegmentCode: "GRC - Incentives"
          roomTypeCode: "DLK"
        - clientCode: "WHG"
          propertyCode: "SAND02CN"
          roomsSold: 5
          arrivals: 7
          departures: 39
          cancellations: 15
          noShows: 16
          roomRevenue: 100.75
          foodRevenue: 201.35
          totalRevenue: 301.42
          occupancyDate: "2020-10-04"
          fiscalDate: "2020-10-02"
          correlationId: "11292d1b6-55c8-4c84-a09c-7bb74403d156"
          noShowRoomRevenue: 502.36
          marketSegmentCode: "GRC - Incentives"
          roomTypeCode: "DLK"