ideas:
  client:
    url: https://pmsinbound-internal.stage.ideasrms.com
    retry:
      period: 5
      maxPeriod: 30
      maxAttempts: 6

spring:
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          pmsInboundAuth:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
            client-authentication-method: post
            scope:
              - com.ideas.api/pms
        provider:
          pmsInboundAuth:
            token-uri: https://fds.stage.ideasrms.com/api/uis/external_m2m/oauth2/token